#!/bin/bash
# Created by MSZ
red='\e[31m'
green='\e[32m'
NC='\e[0m'
echo -e "\e[36m------------------------------------------\e[0m"
MYIP=$(wget -qO- ipv4.icanhazip.com)
passrandom=$(cat /dev/urandom | tr -dc '0-9' | fold -w 6 | head -n 1)

username=TRIAL
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti password
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo -e "  \e[92m__  __  ___  ____ __   __ ___  _  _\e[0m ";
	echo -e " \e[92m|  \/  |/ __||_  / \ \ / /| _ \| \| |\e[0m";
	echo -e " \e[92m| |\/| |\__ \ / /   \ V / |  _/|  \ |\e[0m";
	echo -e " \e[92m|_|  |_||___//___|   \_/  |_|  |_|\_|\e[0m";
	echo -e "                                      ";
	echo -e "          \e[92mTELEGRAM PM @MSZ99\e[0m          ";
	echo -e "   \e[92mTELEGRAM CHANNEL @TELCOBOOSTERVPN\e[0m  ";
	echo -e "    \e[92mTELEGRAM GROUP @TELCO_BOOSTERVPN\e[0m   ";
	echo -e "                                      ";
	echo " ◎ Details For TRIAL Account ◎";
	echo " ";
  echo -e "  \e[34m※\e[0m Username : \e[34m$username\e[0m";
  echo -e "  ${green}※${NC} Password : \e[32m$passrandom\e[0m";
  echo " ";
  echo " ♡ ALWAYS SUPPORTED MSZ99 VPS™ ♡";
	echo " ";
	echo " ";
	echo " ";
	echo " ";
  
else
  useradd TRIAL
  usermod -s /bin/false trial
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo -e "  \e[92m__  __  ___  ____ __   __ ___  _  _\e[0m ";
	echo -e " \e[92m|  \/  |/ __||_  / \ \ / /| _ \| \| |\e[0m";
	echo -e " \e[92m| |\/| |\__ \ / /   \ V / |  _/|  \ |\e[0m";
	echo -e " \e[92m|_|  |_||___//___|   \_/  |_|  |_|\_|\e[0m";
	echo -e "                                      ";
	echo -e "          \e[92mTELEGRAM PM @MSZ99\e[0m          ";
	echo -e "   \e[92mTELEGRAM CHANNEL @TELCOBOOSTERVPN\e[0m  ";
	echo -e "    \e[92mTELEGRAM GROUP @TELCO_BOOSTERVPN\e[0m   ";
	echo -e "                                      ";
	echo " ◎ Details For TRIAL Account ◎";
	echo " ";
  echo -e "  \e[34m※\e[0m Username : \e[34m$username\e[0m";
  echo -e "  ${green}※${NC} Password : \e[32m$passrandom\e[0m";
  echo " ";
  echo " ♡ ALWAYS SUPPORTED MSZ99 VPS™ ♡";
	echo " ";
	echo " ";
	echo " ";
	echo " ";
fi
