#!/bin/bash
red='\e[31m'
green='\e[32m'
blue='\e[34m'
yellow='\e[33m'
NC='\e[0m'
echo -e "\e[36m------------------------------------------\e[0m"
read -p "※ Enter Username To Change : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "※ Enter New Password For User $username : " password
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo -e "  \e[92m__  __  ___  ____ __   __ ___  _  _\e[0m ";
	echo -e " \e[92m|  \/  |/ __||_  / \ \ / /| _ \| \| |\e[0m";
	echo -e " \e[92m| |\/| |\__ \ / /   \ V / |  _/|  \ |\e[0m";
	echo -e " \e[92m|_|  |_||___//___|   \_/  |_|  |_|\_|\e[0m";
	echo -e "                                      ";
	echo -e "          \e[92mTELEGRAM PM @MSZ99\e[0m          ";
	echo -e "   \e[92mTELEGRAM CHANNEL @TELCOBOOSTERVPN\e[0m  ";
	echo -e "    \e[92mTELEGRAM GROUP @TELCO_BOOSTERVPN\e[0m   ";
	echo -e "                                      ";
	echo " ◎ Details For Your Account ◎";
  echo " ";
  echo -e "  \e[34m※\e[0m Username ID  : ${blue}$username${NC}";
  echo -e "  ${green}※${NC} New Password : ${green}$password${NC}";
  echo " ";
  echo " ♡ ALWAYS SUPPORT MSZ99™ SERVER ♡";
  echo " ";
  echo " ";
  echo " ";
  echo " ";

else
echo -e "Username ${red}$username${NC} Does Not Exist"
exit 0
fi
